services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sender:/sender

    command: >
      sh -c "python manage.py test&python manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env.dev

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./sender:/sender
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./.env.dev

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./sender:/sender
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

