# Generated by Django 3.2.16 on 2023-08-01 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+7(\\d{10})')], verbose_name='Номер телефона')),
                ('operator_code', models.CharField(max_length=3, verbose_name='Код оператора')),
                ('teg', models.SlugField(verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_data', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата создания рассылки')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания рассылки')),
                ('client_filter', models.ManyToManyField(related_name='mailing_filter', to='sms_sender.Tag', verbose_name='Данные для фильтрации')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailing', to='sms_sender.message', verbose_name='Сообщение')),
            ],
        ),
    ]
