# Generated by Django 3.2.16 on 2023-08-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_date',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='sms_sender.client', verbose_name='Получатель')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='sms_sender.message', verbose_name='Сообщение')),
            ],
        ),
    ]
