# Generated by Django 3.2.16 on 2023-07-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(max_length=3, verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='teg',
            field=models.SlugField(verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='client_filter',
            field=models.SlugField(verbose_name='Метки для фильтра клиентов'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата создания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailing', to='sms_sender.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
