# Generated by Django 3.2.16 on 2023-07-31 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0004_auto_20230731_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+7(\\d{10})')], verbose_name='Номер телефона'),
        ),
    ]
